### ISSUE TITLE
UCropActivity.setupViews android.content.res.Resources$NotFoundException - Unable to find resource ID #<address> #875

### ISSUE THREAD

**Issue by PrudhviBanki** [jens-muenker/uCrop-n-Edit#12]
UCropActivity.setupViews
android.content.res.Resources$NotFoundException - Unable to find resource ID #

Model:Nexus 5X
Orientation:Portrait
RAM free: 1.28 GB
Disk free: 353.04 MB

Which versions of uCrop, and which Android API versions are affected by this issue? Did this work in previous versions of uCrop?
Lib version: 2.2.6
Android version: 8; 90% and 10; 10%
Device: Nexus 5X

is this issue fixed?

**Comment by jens-muenker** [comment]
I think so, because I have not experienced any bugs or crashes in the current code. If you have any bugs or crashes, please let me now! :)
