### ISSUE TITLE
Java 17 - Compilation failure: class file has wrong version 65.0, should be 61.0

### ISSUE THREAD

**Issue by MyDogTom** [jens-muenker/uCrop-n-Edit#14]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

My project uses Java 17. After updating `uCrop-n-Edit` library from 3.0.5 to 3.0.7, compilation fails with the following error:

```
  bad class file: /Users/.../.gradle/caches/8.8/transforms/73b239a2e9eb733585c8b5b960f922b4/transformed/uCrop-n-Edit-3.0.7-api.jar(/com/yalantis/ucrop/UCrop.class)
    class file has wrong version 65.0, should be 61.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```

Version 61 corresponds to Java 17. Version 65 corresponds to Java 21.

**What is the expected behavior?**

Project should compile as on version 3.0.5.

I assume it happens because uCrop-n-Edit has 
```groovy
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
```

but I'm not familiar with the library publishing process.

**Comment by jens-muenker** [comment]
Yes, you are right. Since version 3.0.6 you have to use at least Java 21 for your project. Otherwise it won't work.

**Comment by MyDogTom** [comment]
Is there any particular reason why the library requires Java 21 and doesn't support Java 17? I'm asking because I believe many Android projects still use Java 17. For example, Google documentation still talks about Java 17 https://developer.android.com/build/jdks. Also if I'm not mistaken, Android Studio comes with the embedded Java 17.

**Comment by jens-muenker** [comment]
No, I just wanted to keep it up to date and my personal projects use Java 21. However, I have now changed it to Java 17 with version [3.0.8](https://github.com/jens-muenker/uCrop-n-Edit/releases/tag/3.0.8). Hope that helps :)

**Comment by MyDogTom** [comment]
Thanks a lot for the new version. I confirm that compilation passes.
