### ISSUE TITLE
Significant APK size increase after 3.0.5 -> 3.0.8 update.

### ISSUE THREAD

**Issue by MyDogTom** [jens-muenker/uCrop-n-Edit#16]
### What is the current behavior?

My release apk increased almost by 10Mb after updating uCrop library from 3.0.5 to 3.0.8. This happens only in build types where minification is enabled.  In the debug apk I see the opposite situration. Apk size decreased because of the removed `armeabi`.

### What is the expected behavior?

APK size should decrease because of the removed `armeabi ` support.

### Root cause analysis

By analysing and comparing apk's  I noticed that new apk includes significant amount of classes from Compose. My App uses Compose, but `uCrop` doesn't, as far as I know. I believe the problems comes from `consumerProguardFiles` configuration in uCrop library. You have these two lines:
```groovy
consumerProguardFiles 'proguard-rules.pro' // in defaultConfig section.
consumerProguardFiles 'proguard-consumer-rules.pro' // in release buildType definition.
```

The resulting consumer Progurad configuration will be a union of `proguard-rules.pro` and `proguard-consumer-rules.pro`. Calling `consumerProguardFiles` doesn't replace the configuration, it adds a new file to the existing configuration.

### Suggested change
I believe there should be only one call of `consumerProguardFiles` with `proguard-consumer-rules.pro`.  `proguard-rules.pro` is just too permissive to be forced to every consumer.

**Comment by MyDogTom** [comment]
In case anyone is looking for a temporary workaround.  You can ignore Proguard rules that come from uCrop library by adding this in `build.gradle`

```Groovy
android {
    defaultConfig {
        optimization {
            keepRules {
                ignoreFrom("com.github.Frosch2010:uCrop-n-Edit")
            }
        }
    }
}
``` 

Remember that in this case you have to add  the missing config to your own Proguard configuration.
```
-dontwarn com.yalantis.ucrop**
-keep class com.yalantis.ucrop** { *; }
-keep interface com.yalantis.ucrop** { *; }
```

**Comment by jens-muenker** [comment]
I am sorry for the delay. I was on holiday. I will look into this next week.

Thank you for finding a workaround. This gives me a bit more time to solve the issue.

**Comment by MyDogTom** [comment]
I confirm that 3.0.9 version resolves the APK size increase issue. Thanks a lot for the update. 🙇
