### ISSUE TITLE
Android 10 crash WindowManager.getCurrentWindowMetrics

### ISSUE THREAD

**Issue by PickupAgency-Admin** [jens-muenker/uCrop-n-Edit#24]
UCrop version: 4.0.2-non-native
Device: Sony android 10

When options.setMaxBitmapSize is not used, lib use **calculateMaxBitmapSize()** in  BitmapLoadUtils.kt
This function use **WindowManager.getCurrentWindowMetrics()** added in SDK 30 (Android 11) and not available in SDK 29 and below

Thanks

**Comment by jens-muenker** [comment]
Sorry, my fault. I made two new versions (4.0.3, 4.0.3-non-native) and fixed this issue.
