### ISSUE TITLE
Update gradle

### ISSUE THREAD

**Issue by jens-muenker** [jens-muenker/uCrop-n-Edit#3]
I attempted to update to the latest gradle version, but I encountered errors on jitpack.io during the publishing process. If anyone has the time and expertise, please consider updating to the latest Gradle version and submitting a pull request.

Thanks for your help! :)

**Comment by TeamRainless** [comment]
On my way to Berlin for a short trip. I'll look into this when I get back.

**Comment by jens-muenker** [comment]
Thanks!
