### ISSUE TITLE
Remove: onActivityResult

### ISSUE THREAD

**Issue by TeamRainless** [jens-muenker/uCrop-n-Edit#6]
Why not just get rid of the  onActivityResult once and for all?

How bout we just go into the place in the original code where it is called... and do something else (literally ANYTHING else) instead?

**Comment by jens-muenker** [comment]
You are right. There is no reason to support it in newer versions of this library. While translating the library, my goal was to encompass all features supported in the latest uCrop version for a seamless transition.

**Comment by TeamRainless** [comment]
It just looks ugly sitting there next to the new, clean code. It also
discourages brand new users from fully understanding how the whole system
really works.

**Comment by jens-muenker** [comment]
This is now in the develop-branch. (See PR #8)
